--Retail Sales Analytics Project

DROP TABLE IF EXISTS retail_sales;
CREATE TABLE retail_sales 
(
    invoice VARCHAR(50),
    stockcode VARCHAR(50),
    description VARCHAR(300),
    quantity INTEGER,
    invoicedate TIMESTAMP,
    price NUMERIC(10,2),
    customer_id INTEGER,
    country VARCHAR(100),
    revenue NUMERIC(12,2),
    order_year INTEGER,
	order_quarter SMALLINT,
    order_month SMALLINT,
    order_month_name VARCHAR(15),
	order_week INT,
    order_day SMALLINT,
    order_day_name VARCHAR(15),
    order_hour SMALLINT,
    top_level_category VARCHAR(100),
    subcategory VARCHAR(100)
);

SELECT*
FROM retail_sales;

--Business Questions

1. What is the total revenue generated by the business?

SELECT
	ROUND(SUM(revenue)) as Total_revenue
FROM retail_sales

2. What are the key business KPIs (Total Revenue, Total Orders, Total Customers, Total Products Sold, and Average Order Value)?

SELECT
	ROUND(SUM(revenue),2) as Total_revenue,
	COUNT(DISTINCT invoice) as Total_orders,
	COUNT(DISTINCT customer_id) as Total_customers,
	COUNT(DISTINCT stockcode) as Total_product_sold,
	ROUND(SUM(revenue)/COUNT(DISTINCT invoice),2) AS average_order_value
FROM retail_sales

3. How has monthly revenue changed over time?

SELECT
	order_year,
	order_month,
	order_month_name,
	ROUND(SUM(revenue),2) as Total_revenue
FROM retail_sales
GROUP BY
	order_year,
	order_month,
	order_month_name
ORDER BY
	order_year,
	order_month

4. Which countries contribute the highest revenue?

SELECT
	country,
	ROUND(SUM(revenue),2) as Total_revenue
FROM retail_sales
GROUP BY 1
ORDER BY 2 DESC
	
5. Which product categories generate the highest revenue?

SELECT
 	top_level_category,
	ROUND(SUM(revenue),2) as Total_revenue
FROM retail_sales
GROUP BY 1
ORDER BY 2 DESC

6. Which products are the top revenue generators?

SELECT
	description,
	ROUND(SUM(revenue),2) as Total_revenue
FROM retail_sales
GROUP BY 1
ORDER BY 2 DESC
LIMIT 15

7. Which products generate low sales despite being available?

SELECT
	description,
	SUM(quantity) AS quantity_sold,
	ROUND(SUM(revenue),2) AS revenue
FROM retail_sales
GROUP BY 1
HAVING SUM(quantity) > 0
ORDER BY 3 ASC
LIMIT 10
	
8. Which customers generate the highest revenue?

SELECT
	customer_id,
	ROUND(SUM(revenue),2) as Total_revenue
FROM retail_sales
WHERE customer_id IS NOT NULL
GROUP BY 1
ORDER BY 2 DESC

9. What percentage of revenue comes from repeat customers?

WITH repeat_customers AS
(
SELECT 
	customer_id
FROM retail_sales
WHERE customer_id IS NOT NULL
GROUP BY customer_id
HAVING COUNT(DISTINCT invoice) > 1
)

SELECT
	ROUND(
	SUM(revenue) *100.0 /
	(SELECT SUM(revenue) FROM retail_sales)
	,2) AS repeat_customer_revenue_percent
FROM retail_sales
WHERE customer_id IN
(
SELECT customer_id
FROM repeat_customers
)

10. What is the average customer spending?

SELECT
	ROUND(AVG(Customer_total),2) AS Average_customer_total
FROM
(
SELECT
	customer_id,
	SUM(revenue) as Customer_total
FROM retail_sales
GROUP BY customer_id
HAVING customer_id IS NOT NULL
)t

11. Which day of the week and hour of the day generate the highest sales?

SELECT
	order_day_name,
	order_hour,
	SUM(revenue) as Total_revenue
FROM retail_sales
GROUP BY
	1,
	2
ORDER BY 3 DESC

12. Which quarter performs the best in terms of revenue?

SELECT
	order_quarter,
	SUM(revenue) as Total_revenue
FROM retail_sales
GROUP BY 1
ORDER BY 2 DESC

13. What is the cancellation rate, and which products are cancelled most often?

--Cancellation Rate--

SELECT
	ROUND(COUNT(*) FILTER(WHERE quantity<0)*100.0/COUNT(*),2) as percentage
FROM retail_sales;  

--Products cancelled most often--

SELECT
	stockcode,
	description,
COUNT(*) AS cancelled_orders
FROM retail_sales
WHERE quantity<0
GROUP BY
	1,
	2
ORDER BY 3 DESC
LIMIT 20

14. How much revenue was lost due to cancelled orders?

SELECT
	ABS(SUM(revenue)) AS cancelled_revenue
FROM retail_sales
WHERE quantity<0

15. Which customers spend above the average customer spend?

SELECT
	customer_id,
	SUM(revenue) AS total_spent
FROM retail_sales
WHERE customer_id IS NOT NULL
GROUP BY customer_id
HAVING
	SUM(revenue)>
	(
	SELECT 
		AVG(customer_total)
	FROM
	(
		SELECT
			customer_id,
			SUM(revenue) customer_total
		FROM retail_sales
		WHERE customer_id IS NOT NULL
		GROUP BY customer_id
	)t
	)	
ORDER BY total_spent DESC

16. Rank the top products within each category using Window Functions.

SELECT
	top_level_category,
	description,
	SUM(revenue) AS total_revenue,
	RANK() OVER( PARTITION BY top_level_category ORDER BY SUM(revenue) DESC) AS product_rank
FROM retail_sales
GROUP BY
	1,
	2

17. Segment customers into High, Medium, and Low Value using a CASE statement.

SELECT
	customer_id,
	SUM(revenue) total_spent,
	CASE
		WHEN SUM(revenue)>=10000 THEN 'High Value'
		WHEN SUM(revenue)>=5000 THEN 'Medium Value'
		ELSE 'Low Value'
	END AS customer_segment
FROM retail_sales
WHERE customer_id IS NOT NULL
GROUP BY 1
ORDER BY 2 DESC

19. Calculate the cumulative (running) revenue over time using Window Functions.

WITH monthly_sales AS
(
	SELECT
		order_year,
		order_month,
		SUM(revenue) as revenue
	FROM retail_sales
	GROUP BY
		order_year,
		order_month
)

SELECT
	order_year,
	order_month,
	revenue,
	SUM(revenue) OVER(ORDER BY order_year, order_month) AS running_revenue
FROM monthly_sales
